Main
thsvr/clone-ny-times pull request #1
Opened 2019-07-23 20:04 UTC by lekegitrepo

Hi,
 we are looking forward to feedback/review.
Best regards.
Thais & Temitayo.

2019-07-24 13:56 UTC, Torres-ssf commented
### Pull Request Under Review By Sérgio (TSE)

2019-07-24 14:18 UTC, Torres-ssf commented
### Great work team 👍
You sure did nicely on this project. But it's not ready yet, we need to make some changes to be in line with Microverse guidelines.

- [ ] Any sections that include text (paragraphs) should be wrapped with a `section` tag and include an `aside` tag for Editor's picks and a Sign-Up button (there are 2 "Editor's picks" in this page, this one lies aside of the main article). 

- [ ] All images and videos should be enclosed by a `figure` tag with `figcaption` that gives a description of the embedded image or video. Not only the images from the main article but also the images from 'More in space and cosmos' and 'Editor's picks'.

- [ ] Your project needs to have the sections 'More in space and cosmos', 'Editor's picks' and 'Most popular'

- [ ] Your footer must have the list links (News, opinion, arts, living, more and subscribe). Use the ul tag. The style must match the original page. It also must include the NY logo(must be a link) and the 'Go to home page' link.

Please kindly make these changes and submit for code review again.

2019-07-26 01:47 UTC, Ispirett commented
Under **Review Ispirerr (Tse)**

2019-07-26 01:56 UTC, Ispirett requested changes

2019-07-26 01:56 UTC, Ispirett commented on index.html
> +	<figure class="inflation-theory">
The image in this section is too big you can make it a little smaller.

2019-07-26 22:53 UTC, Oghenebrume50 commented
reviewing ........

2019-07-26 23:03 UTC, Oghenebrume50 commented on style.css
> +}
Currently the image is titled to the left of the page add `align-items: center` to this style to center it horizontally

2019-07-29 15:27 UTC, merged